import type { UfcEvent } from "./types";

export const CACHE_KEY = "my-homepage-ufc-events-v3";
export const CACHE_TTL = 7 * 24 * 60 * 60 * 1000; // 7 dias

export const UFC_LOGO_URL = "https://a.espncdn.com/i/teamlogos/leagues/500/ufc.png";
export const SILHOUETTE_IMG = "https://a.espncdn.com/combiner/i?img=/i/headshots/nophoto.png&w=350&h=254";

export interface WeightClassInfo {
  namePt: string;
  limit: string;
}

export const WEIGHT_CLASSES_MAP: Record<string, WeightClassInfo> = {
  strawweight: { namePt: "Peso Palha", limit: "Até 52,2 kg" },
  "w strawweight": { namePt: "Peso Palha Feminino", limit: "Até 52,2 kg" },
  "women's strawweight": { namePt: "Peso Palha Feminino", limit: "Até 52,2 kg" },
  flyweight: { namePt: "Peso Mosca", limit: "Até 56,7 kg" },
  "w flyweight": { namePt: "Peso Mosca Feminino", limit: "Até 56,7 kg" },
  "women's flyweight": { namePt: "Peso Mosca Feminino", limit: "Até 56,7 kg" },
  bantamweight: { namePt: "Peso Galo", limit: "Até 61,2 kg" },
  "w bantamweight": { namePt: "Peso Galo Feminino", limit: "Até 61,2 kg" },
  "women's bantamweight": { namePt: "Peso Galo Feminino", limit: "Até 61,2 kg" },
  featherweight: { namePt: "Peso Pena", limit: "Até 65,8 kg" },
  "w featherweight": { namePt: "Peso Pena Feminino", limit: "Até 65,8 kg" },
  "women's featherweight": { namePt: "Peso Pena Feminino", limit: "Até 65,8 kg" },
  lightweight: { namePt: "Peso Leve", limit: "Até 70,3 kg" },
  welterweight: { namePt: "Peso Meio-Médio", limit: "Até 77,1 kg" },
  middleweight: { namePt: "Peso Médio", limit: "Até 83,9 kg" },
  "light heavyweight": { namePt: "Peso Meio-Pesado", limit: "Até 93,0 kg" },
  heavyweight: { namePt: "Peso Pesado", limit: "Até 120,2 kg" },
  catchweight: { namePt: "Peso Casado", limit: "A combinar" },
};

export const COUNTRY_TRANSLATIONS: Record<string, string> = {
  russia: "Rússia",
  china: "China",
  brazil: "Brasil",
  usa: "Estados Unidos",
  "united states": "Estados Unidos",
  japan: "Japão",
  mexico: "México",
  australia: "Austrália",
  canada: "Canadá",
  "new zealand": "Nova Zelândia",
  peru: "Peru",
  mongolia: "Mongólia",
  indonesia: "Indonésia",
  chile: "Chile",
  france: "França",
  armenia: "Armênia",
  "south korea": "Coreia do Sul",
  georgia: "Geórgia",
  england: "Inglaterra",
  "united kingdom": "Reino Unido",
  italy: "Itália",
  uzbekistan: "Uzbequistão",
  morocco: "Marrocos",
  myanmar: "Mianmar",
  argentina: "Argentina",
  poland: "Polônia",
  sweden: "Suécia",
  nigeria: "Nigéria",
  ireland: "Irlanda",
};

export const DEFAULT_MOCK_EVENT: UfcEvent = {
  id: "600060734-default",
  name: "UFC Fight Night: Nurmagomedov vs. Song",
  title: "UFC Xangai",
  subtitle: "Nurmagomedov x Song",
  dateStr: "29/08/2026",
  weekdayStr: "Sábado",
  timeStr: "04:00 (Preliminares) • 07:00 (Principal)",
  isoDate: "2026-08-29T07:00Z",
  venueName: "Shanghai Oriental Sports Center",
  city: "Xangai",
  country: "China",
  broadcast: "Paramount+ / UFC Fight Pass",
  isLive: false,
  statusDescription: "Card Confirmado",
  mainEvent: {
    id: "main-event",
    category: "Bantamweight",
    categoryPt: "Peso Galo",
    weightLimit: "Até 61,2 kg",
    isMainEvent: true,
    rounds: 5,
    fighter1: {
      id: "4569549",
      name: "Umar Nurmagomedov",
      shortName: "U. Nurmagomedov",
      country: "Rússia",
      countryCode: "rus",
      flagUrl: "https://a.espncdn.com/i/teamlogos/countries/500/rus.png",
      record: "20-1-0",
      ranking: "#3",
      headshot: "https://ufc.com/images/styles/event_results_athlete_headshot/s3/2026-01/NURMAGOMEDOV_UMAR_01-24.png?itok=42cWtPfi",
    },
    fighter2: {
      id: "3151289",
      name: "Song Yadong",
      shortName: "S. Yadong",
      country: "China",
      countryCode: "chn",
      flagUrl: "https://a.espncdn.com/i/teamlogos/countries/500/chn.png",
      record: "23-9-1",
      ranking: "#6",
      headshot: "https://ufc.com/images/styles/event_results_athlete_headshot/s3/2026-05/YADONG_SONG_05-30.png?itok=ZSGpgQqR",
    },
    cardSegment: "Card Principal",
  },
  coMainEvent: {
    id: "co-main-event",
    category: "Women's Strawweight",
    categoryPt: "Peso Palha Feminino",
    weightLimit: "Até 52,2 kg",
    isCoMainEvent: true,
    rounds: 3,
    fighter1: {
      id: "4285617",
      name: "Yan Xiaonan",
      shortName: "Y. Xiaonan",
      country: "China",
      countryCode: "chn",
      flagUrl: "https://a.espncdn.com/i/teamlogos/countries/500/chn.png",
      record: "19-5-0",
      ranking: "#4",
      headshot: "https://ufc.com/images/styles/event_results_athlete_headshot/s3/2025-04/XIAONAN_YAN_04-12.png?itok=rKNCv6KF",
    },
    fighter2: {
      id: "4997787",
      name: "Denise Gomes",
      shortName: "D. Gomes",
      country: "Brasil",
      countryCode: "bra",
      flagUrl: "https://a.espncdn.com/i/teamlogos/countries/500/bra.png",
      record: "12-3-0",
      ranking: "#14",
      headshot: "https://ufc.com/images/styles/event_results_athlete_headshot/s3/2025-05/GOMES_DENISE_05-17.png?itok=1ppGctRD",
    },
    cardSegment: "Card Principal",
  },
  allFights: [
    {
      id: "f-13",
      category: "Bantamweight",
      categoryPt: "Peso Galo",
      weightLimit: "Até 61,2 kg",
      isMainEvent: true,
      rounds: 5,
      fighter1: {
        id: "4569549",
        name: "Umar Nurmagomedov",
        country: "Rússia",
        flagUrl: "https://a.espncdn.com/i/teamlogos/countries/500/rus.png",
        record: "20-1-0",
        ranking: "#3",
        headshot: "https://ufc.com/images/styles/event_results_athlete_headshot/s3/2026-01/NURMAGOMEDOV_UMAR_01-24.png?itok=42cWtPfi",
      },
      fighter2: {
        id: "3151289",
        name: "Song Yadong",
        country: "China",
        flagUrl: "https://a.espncdn.com/i/teamlogos/countries/500/chn.png",
        record: "23-9-1",
        ranking: "#6",
        headshot: "https://ufc.com/images/styles/event_results_athlete_headshot/s3/2026-05/YADONG_SONG_05-30.png?itok=ZSGpgQqR",
      },
      cardSegment: "Card Principal",
    },
    {
      id: "f-12",
      category: "Women's Strawweight",
      categoryPt: "Peso Palha Feminino",
      weightLimit: "Até 52,2 kg",
      isCoMainEvent: true,
      rounds: 3,
      fighter1: {
        id: "4285617",
        name: "Yan Xiaonan",
        country: "China",
        flagUrl: "https://a.espncdn.com/i/teamlogos/countries/500/chn.png",
        record: "19-5-0",
        ranking: "#4",
        headshot: "https://ufc.com/images/styles/event_results_athlete_headshot/s3/2025-04/XIAONAN_YAN_04-12.png?itok=rKNCv6KF",
      },
      fighter2: {
        id: "4997787",
        name: "Denise Gomes",
        country: "Brasil",
        flagUrl: "https://a.espncdn.com/i/teamlogos/countries/500/bra.png",
        record: "12-3-0",
        ranking: "#14",
        headshot: "https://ufc.com/images/styles/event_results_athlete_headshot/s3/2025-05/GOMES_DENISE_05-17.png?itok=1ppGctRD",
      },
      cardSegment: "Card Principal",
    },
    {
      id: "f-11",
      category: "Bantamweight",
      categoryPt: "Peso Galo",
      weightLimit: "Até 61,2 kg",
      rounds: 3,
      fighter1: {
        id: "4898177",
        name: "Kai Asakura",
        country: "Japão",
        flagUrl: "https://a.espncdn.com/i/teamlogos/countries/500/jpn.png",
        record: "22-6-0",
        headshot: "https://ufc.com/images/styles/event_results_athlete_headshot/s3/2026-05/ASAKURA_KAI_05-30.png?itok=zK8HdTe4",
      },
      fighter2: {
        id: "4294025",
        name: "Aoriqileng",
        country: "China",
        flagUrl: "https://a.espncdn.com/i/teamlogos/countries/500/chn.png",
        record: "26-13-0",
        headshot: "https://ufc.com/images/styles/event_results_athlete_headshot/s3/2026-05/AORIQILENG_05-30.png?itok=jnMfPR3X",
      },
      cardSegment: "Card Principal",
    },
    {
      id: "f-10",
      category: "Flyweight",
      categoryPt: "Peso Mosca",
      weightLimit: "Até 56,7 kg",
      rounds: 3,
      fighter1: {
        id: "2560751",
        name: "Alex Perez",
        country: "Estados Unidos",
        flagUrl: "https://a.espncdn.com/i/teamlogos/countries/500/usa.png",
        record: "26-10-0",
        ranking: "#11",
        headshot: "https://ufc.com/images/styles/event_results_athlete_headshot/s3/2026-05/PEREZ_ALEX_05-30.png?itok=JXcr39bS",
      },
      fighter2: {
        id: "4376483",
        name: "Sumudaerji",
        country: "China",
        flagUrl: "https://a.espncdn.com/i/teamlogos/countries/500/chn.png",
        record: "19-7-0",
        headshot: "https://ufc.com/images/styles/event_results_athlete_headshot/s3/2026-05/SUMUDAERJI_05-30.png?itok=RG80cBip",
      },
      cardSegment: "Card Principal",
    },
    {
      id: "f-9",
      category: "Light Heavyweight",
      categoryPt: "Peso Meio-Pesado",
      weightLimit: "Até 93,0 kg",
      rounds: 3,
      fighter1: {
        id: "4898188",
        name: "Junior Tafa",
        country: "Austrália",
        flagUrl: "https://a.espncdn.com/i/teamlogos/countries/500/aus.png",
        record: "7-6-0",
        headshot: "https://ufc.com/images/styles/event_results_athlete_headshot/s3/2026-06/TAFA_JUNIOR_06-06.png?itok=qpC8jJJp",
      },
      fighter2: {
        id: "5300001",
        name: "Ce Liu",
        country: "China",
        flagUrl: "https://a.espncdn.com/i/teamlogos/countries/500/chn.png",
        record: "3-1-0",
      },
      cardSegment: "Card Principal",
    },
    {
      id: "f-8",
      category: "Flyweight",
      categoryPt: "Peso Mosca",
      weightLimit: "Até 56,7 kg",
      rounds: 3,
      fighter1: {
        id: "5300002",
        name: "Bilal Hasan",
        country: "Indonésia",
        flagUrl: "https://a.espncdn.com/i/teamlogos/countries/500/ina.png",
        record: "9-0-0",
        headshot: "https://ufc.com/images/styles/event_results_athlete_headshot/s3/2026-08/HASAN_BILAL_08-11.png?itok=8pvJBrNm",
      },
      fighter2: {
        id: "5300003",
        name: "Nilson Rojas",
        country: "Chile",
        flagUrl: "https://a.espncdn.com/i/teamlogos/countries/500/chi.png",
        record: "9-0-0",
      },
      cardSegment: "Preliminares",
    },
    {
      id: "f-7",
      category: "Flyweight",
      categoryPt: "Peso Mosca",
      weightLimit: "Até 56,7 kg",
      rounds: 3,
      fighter1: {
        id: "5300004",
        name: "Namsrai Batbayar",
        country: "Mongólia",
        flagUrl: "https://a.espncdn.com/i/teamlogos/countries/500/mgl.png",
        record: "9-1-0",
        headshot: "https://ufc.com/images/styles/event_results_athlete_headshot/s3/2026-01/BATBAYAR_NAMSRAI_01-31.png?itok=gtDdNT2H",
      },
      fighter2: {
        id: "5133604",
        name: "André Lima",
        country: "Brasil",
        flagUrl: "https://a.espncdn.com/i/teamlogos/countries/500/bra.png",
        record: "11-1-0",
        headshot: "https://ufc.com/images/styles/event_results_athlete_headshot/s3/2026-06/LIMA_ANDRE_06-20.png?itok=i1kMEi1J",
      },
      cardSegment: "Preliminares",
    },
    {
      id: "f-6",
      category: "Flyweight",
      categoryPt: "Peso Mosca",
      weightLimit: "Até 56,7 kg",
      rounds: 3,
      fighter1: {
        id: "5085352",
        name: "Rei Tsuruya",
        country: "Japão",
        flagUrl: "https://a.espncdn.com/i/teamlogos/countries/500/jpn.png",
        record: "11-1-0",
        headshot: "https://ufc.com/images/styles/event_results_athlete_headshot/s3/2026-05/TSURUYA_REI_05-30.png?itok=EeEPY_iV",
      },
      fighter2: {
        id: "5126861",
        name: "Kevin Borjas",
        country: "Peru",
        flagUrl: "https://a.espncdn.com/i/teamlogos/countries/500/per.png",
        record: "11-5-0",
        headshot: "https://ufc.com/images/styles/event_results_athlete_headshot/s3/2026-06/BORJAS_KEVIN_06-20.png?itok=efbTVP2q",
      },
      cardSegment: "Preliminares",
    },
    {
      id: "f-5",
      category: "Featherweight",
      categoryPt: "Peso Pena",
      weightLimit: "Até 65,8 kg",
      rounds: 3,
      fighter1: {
        id: "4416174",
        name: "Sean Woodson",
        country: "Estados Unidos",
        flagUrl: "https://a.espncdn.com/i/teamlogos/countries/500/usa.png",
        record: "13-2-1",
        headshot: "https://ufc.com/images/styles/event_results_athlete_headshot/s3/2025-04/WOODSON_SEAN_04-12.png?itok=v59spZeC",
      },
      fighter2: {
        id: "4995574",
        name: "Jack Jenkins",
        country: "Austrália",
        flagUrl: "https://a.espncdn.com/i/teamlogos/countries/500/aus.png",
        record: "14-4-0",
      },
      cardSegment: "Preliminares",
    },
    {
      id: "f-4",
      category: "Bantamweight",
      categoryPt: "Peso Galo",
      weightLimit: "Até 61,2 kg",
      rounds: 3,
      fighter1: {
        id: "5126888",
        name: "Xiao Long",
        country: "China",
        flagUrl: "https://a.espncdn.com/i/teamlogos/countries/500/chn.png",
        record: "27-11-0",
      },
      fighter2: {
        id: "5133610",
        name: "Francesco Nuzzi",
        country: "Itália",
        flagUrl: "https://a.espncdn.com/i/teamlogos/countries/500/ita.png",
        record: "11-2-0",
      },
      cardSegment: "Preliminares",
    },
    {
      id: "f-3",
      category: "Bantamweight",
      categoryPt: "Peso Galo",
      weightLimit: "Até 61,2 kg",
      rounds: 3,
      fighter1: {
        id: "5300005",
        name: "Lawrence Lui",
        country: "Nova Zelândia",
        flagUrl: "https://a.espncdn.com/i/teamlogos/countries/500/nzl.png",
        record: "8-1-0",
      },
      fighter2: {
        id: "5300006",
        name: "Hector Santiago",
        country: "Brasil",
        flagUrl: "https://a.espncdn.com/i/teamlogos/countries/500/bra.png",
        record: "6-1-0",
      },
      cardSegment: "Preliminares",
    },
    {
      id: "f-2",
      category: "Women's Strawweight",
      categoryPt: "Peso Palha Feminino",
      weightLimit: "Até 52,2 kg",
      rounds: 3,
      fighter1: {
        id: "5300007",
        name: "Jingnan Xiong",
        country: "China",
        flagUrl: "https://a.espncdn.com/i/teamlogos/countries/500/chn.png",
        record: "19-3-0",
      },
      fighter2: {
        id: "4714163",
        name: "Julia Polastri",
        country: "Brasil",
        flagUrl: "https://a.espncdn.com/i/teamlogos/countries/500/bra.png",
        record: "14-6-0",
        headshot: "https://ufc.com/images/styles/event_results_athlete_headshot/s3/2024-06/POLASTRI_JULIA_06-15.png",
      },
      cardSegment: "Preliminares",
    },
    {
      id: "f-1",
      category: "Welterweight",
      categoryPt: "Peso Meio-Médio",
      weightLimit: "Até 77,1 kg",
      rounds: 3,
      fighter1: {
        id: "5300008",
        name: "Ding Meng",
        country: "China",
        flagUrl: "https://a.espncdn.com/i/teamlogos/countries/500/chn.png",
        record: "35-10-0",
      },
      fighter2: {
        id: "5300009",
        name: "Cameron Nelson",
        country: "Canadá",
        flagUrl: "https://a.espncdn.com/i/teamlogos/countries/500/can.png",
        record: "7-1-0",
      },
      cardSegment: "Preliminares",
    },
  ],
};
